# Generated by Django 4.2 on 2026-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contactlink_project_skill_sociallink_stat"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("occurred_at", models.DateTimeField()),
                ("kafka_topic", models.CharField(blank=True, max_length=200)),
                ("kafka_partition", models.IntegerField(blank=True, null=True)),
                ("kafka_offset", models.BigIntegerField(blank=True, null=True)),
                ("appointment_id", models.CharField(max_length=100)),
                ("user_id", models.CharField(blank=True, max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_e164", models.CharField(blank=True, max_length=30)),
                ("notify_email", models.BooleanField(default=False)),
                ("notify_sms", models.BooleanField(default=False)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
