# Generated by Django 4.2.28 on 2026-03-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_project_body_project_category_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
